[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
omit = [
    "setup.py",
]

[tool.pytest.ini_options]
addopts = "-s -vv -p"
minversion = "6.0"
testpaths = ["tests"]