name: adbcug_adapter_dev
channels:
- nvidia
- rapidsai
- numba
- conda-forge
dependencies:
- cudatoolkit>=11.2
- cugraph>=21.12.00
- python>=3.7,<3.10
- python-arango>=7.3.4
- pip
- pytest>=6.0.0
- setuptools>=42