name: build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'adbcug_adapter/**'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - 'pyproject.toml'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'adcug_adapter/**'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - 'pyproject.toml'
      - '.github/workflows/build.yml'
env:
  PACKAGE_DIR: adbcug_adapter
  TESTS_DIR: tests
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]
    name: gpu
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda env list
          conda activate ${{ matrix.python }}
          pip install .[dev]
      - name: Run black
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate ${{ matrix.python }}
          black --version
          black --check --verbose --diff --color ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}
      - name: Run flake8
        run: flake8 ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}
      - name: Run isort
        run: isort --check --profile=black ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}
      - name: Run mypy
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate ${{ matrix.python }}
          mypy ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}
      - name: Run pytest in conda env
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate ${{ matrix.python }}
          conda run -n ${{ matrix.python }} py.test -k "test_cug_to_adb" --cov=${{env.PACKAGE_DIR}} --cov-report xml --cov-report term-missing -v --color=yes --no-cov-on-fail --code-highlight=yes
      - name: Publish to coveralls.io
        if: matrix.python == '3.8'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: conda run -n ${{ matrix.python }} coveralls --service=github
