name: build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PACKAGE_DIR: adbcug_adapter
  TESTS_DIR: tests
jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - python: "3.8"
            container: "rapidsai/rapidsai:cuda11.8-runtime-ubuntu22.04-py3.8"

          - python: "3.9"
            container: "rapidsai/rapidsai:cuda11.8-runtime-ubuntu22.04-py3.9"

          - python: "3.10"
            container: "rapidsai/rapidsai:cuda11.8-runtime-ubuntu22.04-py3.10"

    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install packages
        run: pip install -e '.[dev]'
      # - name: Run black
      #   run: black --check --verbose --diff --color ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}
      # - name: Run flake8
      #   run: flake8 ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}
      # - name: Run isort
      #   run: isort --check --profile=black ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}
      # - name: Run mypy
      #   run: mypy ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}
      # - name: Setup Docker
      #   uses: docker/setup-buildx-action@v2.8.0
      # - name: Set up ArangoDB Instance via Docker
      #   run: docker create --name adb -p 8529:8529 -e ARANGO_ROOT_PASSWORD= arangodb/arangodb
      # - name: Start ArangoDB Instance
      #   run: docker start adb
      - name: Run pytest
        run: pytest --cov=${{env.PACKAGE_DIR}} --cov-report xml --cov-report term-missing -v --color=yes --no-cov-on-fail --code-highlight=yes
      - name: Publish to coveralls.io
        if: matrix.python == '3.8'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: conda run -n ${{ matrix.python }} coveralls --service=github
