name: release
on: [workflow_dispatch]
env:
  PACKAGE_DIR: adbcug_adapter
  TESTS_DIR: tests
jobs:
  release:
    needs: build
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    name: release
    steps:
      - uses: actions/checkout@v2
      - name: Fetch complete history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Conda Build
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate "3.9"
          conda install conda-build anaconda-client conda-verify -y
          conda build .