name: condabuild
on: [push]
env:
  PACKAGE_DIR: adbcug_adapter
  TESTS_DIR: tests
jobs:
  condabuild:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    name: condabuild
    steps:
      - uses: actions/checkout@v2
      - name: Fetch complete history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Conda Build
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda create -n cbuild python=3.9
          conda activate cbuild
          conda install -c nvidia -c rapidsai -c numba -c conda-forge cugraph cudatoolkit=11.5
          conda info
          conda list