name: condabuild
on: [push]
env:
  PACKAGE_DIR: adbcug_adapter
  TESTS_DIR: tests
jobs:
  condabuild:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    name: condabuild
    steps:
      - uses: actions/checkout@v2
      - name: Fetch complete history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Conda Build
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda create -n condabuild39 python=3.9
          conda activate condabuild39
          conda run python --version
          conda config --set channel_priority false
          conda config --add channels nvidia
          conda config --add channels rapidsai
          conda config --add channels numba
          conda config --add channels conda-forge
          conda list
          conda info